/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface CriteriaResponse {
  id?: number;
  criteriaIdentifier?: number;
  name?: string;
  description?: string;
  weight?: number;
  min?: number;
  max?: number;
}
