/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface RankResponse {
  id?: number;
  rankIdentifier?: number;
  level?: number;
  xpFrom?: number;
  name?: string;
}
