/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { CriteriaResponse } from "./criteriaResponse";
import type { RankResponse } from "./rankResponse";

export interface ServiceProviderResponse {
  id?: number;
  contractIdentifier?: number;
  name?: string;
  owner?: string;
  description?: string;
  websiteURL?: string;
  criterias?: CriteriaResponse[];
  ranks?: RankResponse[];
  active?: boolean;
}
