/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { FieldValidationError } from "./fieldValidationError";

export interface ValidationDetail {
  message?: string;
  timestamp?: string;
  fieldValidations?: FieldValidationError[];
}
